# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/183UZ0o3UI37fVY7cxlMs0evbZyCGfL0a
"""

name="Priya"
age=19
CGPA=8.5
placed=True
print("Student Name:",name)
print("Age:",age)
print("CGPA:",CGPA)
print("Placed",placed)
print(type(name))
print(type(age))
print(type(CGPA))
print(type(placed))

