# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LfMTZ5kd8HVZqaF9e-hCazmAqtCHcN0Z
"""

List

name=["Priya","Boomi","Madhu"]
name.append("Bavani")
marks=[50,40,80]
print(name)
print(marks[2])
print(len(name))
print(len(marks))

Tuple

days=("Monday","Tuesday","Wednesday")
print(days[1])

Dictionary

student={
    "name":"Priya",
    "age":19
}