# -*- coding: utf-8 -*-
"""Internship day-3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1STXOFRjL45qNSccl_xAEGTbMpuNv6UjB
"""

import numpy as np
marks=np.array([80,40,30,89])
print(marks)

import numpy as np
a=np.array([1,2,3])
b=np.array([5,6,7])
print(a+b)